# 1. NumPy Library

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip list

Package                       VersionNote: you may need to restart the kernel to use updated packages.

----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.wea

In [3]:
conda install numPy


jupyter-client                6.1.12
jupyter-console               6.4.0
jupyter-core                  4.9.2
jupyter-server                1.13.5
jupyterlab                    3.3.2
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
jupyterlab-widgets            1.0.0
keyring                       23.4.0
kiwisolver                    1.3.2
lazy-object-proxy             1.6.0
libarchive-c                  2.9
llvmlite                      0.38.0
locket                        0.2.1
lxml                          4.8.0
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.5.1
matplotlib-inline             0.1.2
mccabe                        0.6.1
menuinst                      1.4.18
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mock                          4.0.3
mpmath                        1.2.1
msgpack                


CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https//repo.anaconda.com/pkgs/main/win-64'




In [4]:
import numpy as np

In [5]:
print(np.__version__)

1.21.5


In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
print(np.amin(arr))

1


In [9]:
print(np.amax(arr))

10


In [10]:
print(np.mean(arr))

5.5


In [11]:
print(np.median(arr))

5.5


In [12]:
print(np.ptp(arr))

9


In [13]:
print(np.std(arr))

2.8722813232690143


In [14]:
print(np.var(arr))

8.25


In [15]:
print(np.average(arr))

5.5


In [16]:
print(np.percentile(arr))

TypeError: _percentile_dispatcher() missing 1 required positional argument: 'q'

In [17]:
print(np.percentile(arr))

TypeError: _percentile_dispatcher() missing 1 required positional argument: 'q'

In [18]:
print(np.amin(arr))
print(np.amax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.ptp(arr))
print(np.std(arr))
print(np.var(arr))
print(np.average(arr))
print(np.percentile(arr,5))

1
10
5.5
5.5
9
2.8722813232690143
8.25
5.5
1.45


# 2. Statistical Function

### NumPy  - numerical python libraries

In [19]:
#creat simple array from the list 

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
#diamension of the array

print(arr.ndim)

2


In [21]:
#Shape of the array

print(arr.shape)

(2, 4)


In [22]:
#type of the array

print(type(arr))

<class 'numpy.ndarray'>


In [23]:
#data of the array

print(arr.data)

# 3. Matrics Operations

### Random Number Generator using NumPy

In [24]:
from numpy import random
x= random.randint(100)
print(x)

99


In [25]:
from numpy import random
x= random.randint(50)
print(x)

20


In [26]:
from numpy import random
x= random.randint(75)
print(x)

8


In [27]:
from numpy import random
x= random.randint(15)
print(x)

5


In [28]:
from numpy import random
x= random.randint(26)
print(x)

8


In [29]:
from numpy import random
x= random.randint(26)
print(10)

10


In [30]:
from numpy import random
x= random.randint(2)
print(x)

1


In [31]:
#Generate Random Float

x= random.rand(10)
print(x)

[0.50867947 0.61182767 0.30168282 0.01199598 0.19372477 0.67036006
 0.07821792 0.18572468 0.4689554  0.24597754]


In [32]:
#Generate Random Array

from numpy import random
x= random.randint(100, size=(5))
print(x)

[30 42 32 71 74]


In [33]:
from numpy import random
x= random.randint(100, size=(10))
print(x)

[24 46 43 90 86 15 74 32 46 83]


In [34]:
from numpy import random
x= random.randint(50, size=(10))
print(x)

[48 20 10 29 43 42 26 48 48  4]


In [35]:
#Generate a 2-D array with 3 rows, Each row containing 5 random in value

from numpy import random
x= random.randint(100, size=(3, 5))
print(x)

[[62  9 15 86 25]
 [85 55 65 66 12]
 [69 83 24 91 97]]


In [36]:
from numpy import random
x= random.randint(100, size=(4, 4))
print(x)

[[76 72 65 81]
 [41 35 55  2]
 [91 26 52 98]
 [39 86 10 37]]


In [37]:
from numpy import random
x= random.randint(50, size=(5, 10))
print(x)

[[40 15 12  6 14 47 30 31 41 43]
 [20 47 10 23 45 28 20 16 19 42]
 [17 27 32 14  8 44 24 34 47  7]
 [36 47 21  1 11 31 12 39 48 22]
 [33 33 38  0 47 21 35 18 30 38]]


Seed function for remain same the row and column 

In [38]:
from numpy import random
random.seed(101)
x= random.randint(50, size=(5, 10))
print(x)

[[31 11 17  6 23 11 47  9 13 40]
 [ 4 40 28  0 46  5 12 29 40 49]
 [19 47  8 29 34 44  8 19 10 12]
 [31 43 23  0 41  9 47  8 36 19]
 [35 28  7 10 39 38 46  9 18  7]]


In [39]:
from numpy import random
random.seed(101)
x= random.randint(50, size=(6, 10))
print(x)

[[31 11 17  6 23 11 47  9 13 40]
 [ 4 40 28  0 46  5 12 29 40 49]
 [19 47  8 29 34 44  8 19 10 12]
 [31 43 23  0 41  9 47  8 36 19]
 [35 28  7 10 39 38 46  9 18  7]
 [39 15 44  0 42 12 17 11 15 33]]


### PRACTICAL: Creating scalars in Numpy

In [40]:
#import numpy

#Creating 1-D list
list1 = [1,2,3]

#Creating 1-D list vertical
list2 = ([10],
        [20],
        [30])

#Creat vector1

vector1 = np.array(list1)
vector2 = np.array(list2)

print("Horizontal vector")
print(vector1)

print("-------------")

print("vertical vector")
print(vector2)



Horizontal vector
[1 2 3]
-------------
vertical vector
[[10]
 [20]
 [30]]


In [41]:
a=np.matrix('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [42]:
a= np.matrix('1 2;3 4')
print("via string input : \n", a, "\n")

#array-like input
b= np.matrix([[5, 6, 7], [4, 6]])
print("via array-like input :\n", b)

via string input : 
 [[1 2]
 [3 4]] 

via array-like input :
 [[list([5, 6, 7]) list([4, 6])]]


C:\Users\Shiv\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


In [43]:
a= np.matrix('1 2;3 4')
print("via string input : \n", a, "\n")

#array-like input
b=np.matrix([[5, 6, 7], 
             [4, 6]])
print("via array-like input :\n", b)

via string input : 
 [[1 2]
 [3 4]] 

via array-like input :
 [[list([5, 6, 7]) list([4, 6])]]


 ### Matrix Multiplication in Numpy

In [44]:
A = 5

B = [[6, 7],
     [8, 9]]

print(np.dot(A,B))

[[30 35]
 [40 45]]


In [45]:
A = [[6, 7],
     [8, 9]]

B = [[1, 3],
     [5, 7]]

print(np.dot(A,B))

print("---------")

print(np.dot(B,A))

[[41 67]
 [53 87]]
---------
[[30 34]
 [86 98]]


In [46]:
B = 5

A = [[6, 7],
     [8, 9]]

print(np.dot(B,A))

[[30 35]
 [40 45]]


In [47]:
A= ([1,2,3],[4,5,6],[7,8,9])

np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
import numpy as np

A= ([1,2,3],[4,5,6],[7,8,9,4])

np.transpose(A)

C:\Users\Shiv\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 4])], dtype=object)

### Percentile & interquartile in NumPy

In [49]:
import numpy as np

data= [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

#first quartile(Q1)

Q1= np.median(data[:10])
print(Q1)

25.5


In [50]:
#Third Qurtile(Q3)
Q3= np.median(data[10:])
print(Q3)

35.5


In [51]:
#interqurtile range

IQR = Q3-Q1
print(IQR)

10.0


In [52]:
data= [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

#first quartile(Q1)
Q1= np.median(data[:10])
print(Q1, '\n')

#Third Qurtile(Q3)
Q3= np.median(data[10:])
print(Q3, '\n')

#interqurtile range
IQR = Q3-Q1
print("IQR = Q3-Q1 =",IQR)

25.5 

35.5 

IQR = Q3-Q1 = 10.0


# 4. Array Broadcasting in Numpy

In [53]:
a = np.array([1.1, 2.0, 3.0])
b = np.array([2.0, 2.1, 2.1])

a*b

array([2.2, 4.2, 6.3])

In [54]:
a = np.array([1.0, 2.0, 3.0])
b = 2.1

a*b

array([2.1, 4.2, 6.3])

# 5. Calculate BMI of cricket players

In [55]:
#Heights of Players

Hg_in = [61, 65, 64, 69, 70, 68, 64, 63, 62, 66, 72]  #in = inch

#Convert into numpy array

ht_np = np.array(Hg_in)

#Convert height from inch to meter by exposing it to 0.0245
ht_np = ht_np*0.0245

ht_np

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [56]:
#weight of players in pound

wt_pd = [101,201,161,170,180,141,156,168,175,180,200]

#Convert into numpy array
wt_np = np.array(wt_pd)

#Convert weight from pound to kg by exposing it to 0.45
wt_np = wt_np*0.45

wt_np

array([45.45, 90.45, 72.45, 76.5 , 81.  , 63.45, 70.2 , 75.6 , 78.75,
       81.  , 90.  ])

In [57]:
#BMI calculation

BMI = wt_np/(ht_np**2)
BMI

array([20.34895207, 35.6656127 , 29.46770226, 26.76893449, 27.5395456 ,
       22.86028457, 28.55255623, 31.73280974, 34.12989992, 30.97882769,
       28.92313388])

In [58]:
BMI[-1]

28.923133879402098

In [59]:
players = np.array([wt_np, ht_np])
players

array([[45.45  , 90.45  , 72.45  , 76.5   , 81.    , 63.45  , 70.2   ,
        75.6   , 78.75  , 81.    , 90.    ],
       [ 1.4945,  1.5925,  1.568 ,  1.6905,  1.715 ,  1.666 ,  1.568 ,
         1.5435,  1.519 ,  1.617 ,  1.764 ]])

In [60]:
players [0][2]

72.45

In [61]:
players [1][3]

1.6905000000000001

In [62]:
players [0]

array([45.45, 90.45, 72.45, 76.5 , 81.  , 63.45, 70.2 , 75.6 , 78.75,
       81.  , 90.  ])

In [63]:
players [1]

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [64]:
#transpose

pt = players.transpose()
pt.shape

(11, 2)

In [65]:
pt = players.transpose()
pt

array([[45.45  ,  1.4945],
       [90.45  ,  1.5925],
       [72.45  ,  1.568 ],
       [76.5   ,  1.6905],
       [81.    ,  1.715 ],
       [63.45  ,  1.666 ],
       [70.2   ,  1.568 ],
       [75.6   ,  1.5435],
       [78.75  ,  1.519 ],
       [81.    ,  1.617 ],
       [90.    ,  1.764 ]])

In [66]:
#statestical & mathamatical function on plyers data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))

#standard deviation
print(np.std(wt_np))

#corelation cofficient
print(np.corrcoef(wt_np,ht_np))

74.98636363636363
76.5
824.85
12.01711073483236
[[1.         0.50899917]
 [0.50899917 1.        ]]


### Self Practice Calculation of campus rooms

In [67]:
import numpy as np
#length of classrooms

len_m = [10,11,12,13,14,15,16,17,18,19]
len_np = np.array(len_m)
len_np

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
#width of classrooms

wid_m = [20,21,22,23,24,25,26,27,28,29]
wid_np = np.array(wid_m)
wid_np

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
#height of classrooms

hei_m = [30,30,30,30,30,30,30,30,30,30]
hei_np = np.array(hei_m)
hei_np

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30])

In [70]:
volume = len_np * wid_np * hei_np
volume

array([ 6000,  6930,  7920,  8970, 10080, 11250, 12480, 13770, 15120,
       16530])